export const GURBANI_SEARCH = "GURBANI_SEARCH";
export const SEARCH_SHABAD_PANKTI = "SEARCH_SHABAD_PANKTI";

export const SHABAD_AUTO_NEXT = "SHABAD_AUTO_NEXT";
export const SHABAD_HOME = "SHABAD_HOME";
export const SHABAD_PREV = "SHABAD_PREV";
export const SHABAD_SET_HOME = "SHABAD_SET_HOME";
export const SHABAD_NEXT = "SHABAD_NEXT";
export const SHABAD_UPDATE = "SHABAD_UPDATE";
export const SHABAD_PANKTI = "SHABAD_PANKTI";

export const SET_APP_PAGE = "SET_APP_PAGE";
export const TOGGLE_PANEL = "TOGGLE_PANEL";

export const REMOVE_RECENT_PANKTI = "REMOVE_RECENT_PANKTI";
export const CLEAR_RECENT_PANKTIS = "CLEAR_RECENT_PANKTIS";

export const RECENT_SEARCH_UPDATE = "RECENT_SEARCH_UPDATE";
